name: Linux kernel CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install depedencies
      run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            flex \
            bison \
            libssl-dev \
            libelf-dev \
            libncurses-dev \
            dwarves
    - name: Configure kernel
      run: cp .github/workflows/x86_config .config
            
    - name: Build kernel
      run: |
        make olddefconfig
        make -j"$(nproc)"
